reports/library/taxon_groups/filterable_group_counts.xml
E.g. if additional joins added by the report filter
=> Ensured taxon group field not ambiguous

reports/library/users/filterable_record_counts_by_website_survey.xml
Lists users by all available website and surveys, with a record count.
Standard filter options.
=> Added a users report

reports/reports_for_prebuilt_forms/Splash/mean_cover_value_per_species_per_broad_habitat.xml, reports/reports_for_prebuilt_forms/Splash/mean_cover_value_per_species_per_fine_habitat.xml, reports/reports_for_prebuilt_forms/Splash/number_of_plots_per_species.xml, reports/reports_for_prebuilt_forms/Splash/occupied_squares_per_species.xml
Improved website filter to hopefully improve performance of some NPMS reports (although can't really tell if it will on my own machine with limited data)
=> Improved website filter to improve NPMS report performance

reports/library/locations/locations_list_mapping.xml, reports/library/locations/locations_list_mapping_lores.xml
No need for colour cycling - its arbitrary and begs further questions
=> Unnecessary colours on locations list map removed

application/models/location.php, application/models/occurrence.php, application/models/person.php, application/models/sample.php, application/models/survey.php, application/models/taxa_taxon_list.php
Attribute field prefix must be public as it is used during import
to detect changes in sample information between records.
=> Fixes #16. Import of records with diff sample details.

application/config/version.php, modules/indicia_svc_data/controllers/services/data.php
Array map function did not return result so did not work.
=> Fix to existing code which checked file types against config

modules/rest_api_sync/controllers/services/rest_api_sync.php
* Removal of done todos
* Lookup against correct taxon_list_id for comment TVK.
* Syntax fix
=> Feature rest api

modules/cache_builder/db/version_0_1_2/201511031951_fix_output_sref.sql, modules/indicia_setup/db/version_0_9_1/201511040918_sref_system_to_srid.sql
Additional tidying of map_square cleanup scripts
=> Hotfix map squares

application/config/version.php, modules/indicia_setup/db/version_0_9_1/201511231004_sref_system_to_srid.sql
Fixes #42 - mtbqqq support when building cache_occurrences
=> Hotfix mtbqqq

modules/indicia_setup/db/version_0_9_1/201511231408_function_volatility.sql
Potential performance improvements.
=> Fixes #44 - corrects function volatility

modules/indicia_svc_data/controllers/services/report.php, modules/request_logging/config/.gitignore, modules/request_logging/config/request_logging.example.php, modules/request_logging/db/version_0_1_0/201511242046_request_log.sql, modules/request_logging/helpers/request_logging.php
Includes implementation for logging report requests.
=> Module for logging web service requests

modules/indicia_setup/db/version_0_9_1/201512011332_group_licence.sql, modules/indicia_setup/db/version_0_9_1/201512011332_sample_licence.sql
=> Feature licenses

application/models/sample.php
* Was causing errors on save of a sample e.g. if not a logged in Drupal
user.
* Also reviewed todos and removed them - performance good as uses an
index (0.3ms impact measured)
=> Fixes saving samples with anonymous user

reports/library/occurrences/filterable_explore_list.xml
Added class zero-t to taxon name columns for occurrence list when
record was zero.
=> Zero abundance classes added to filterable occurrence list report

application/config/version.php, application/libraries/ReportEngine.php, application/libraries/XMLReportReader.php, reports/reports_for_prebuilt_forms/Track_A_Tree/tree_download2.xml, reports/reports_for_prebuilt_forms/UKBMS/ukbms_timed_counts_download.xml
Second attempt... Allows second table to access standard attribute processing in reports for samples, locations and occurrences.
=> Hotfix report second attributes

application/libraries/ReportEngine.php, modules/spatial_index_builder/db/version_0_1_0/201512091144_location_type_id.sql, reports/library/occurrences/filterable_nbn_exchange.xml, reports/library/occurrences/filterable_occurrences_download.xml, reports/library/occurrences/filterable_occurrences_download_gis.xml, reports/library/occurrences/filterable_occurrences_download_parent_samples.xml, reports/library/occurrences/filterable_occurrences_download_sensitive.xml, reports/library/occurrences/nbn_exchange.xml, reports/library/occurrences/nbn_exchange_by_input_date.xml, reports/library/occurrences/nbn_exchange_by_input_date_using_spatial_index_builder.xml, reports/library/occurrences/occurrences_download_2.xml, reports/library/occurrences/occurrences_download_2_by_input_date.xml, reports/library/occurrences/occurrences_download_2_by_input_date_using_spatial_index_builder.xml, reports/library/occurrences/occurrences_download_2_gis.xml
Improves way that system function attributes are added to query joins in downloads
Adds location_type_id to index_locations_samples - better report join performance.
=> Download reporting performance

application/libraries/ReportEngine.php, reports/library/occurrences/filterable_occurrences_download.xml, reports/library/occurrences/filterable_occurrences_download_gis.xml, reports/library/occurrences/filterable_occurrences_download_parent_samples.xml, reports/library/occurrences/filterable_occurrences_download_sensitive.xml
Code was lost during merge of 2 hot fixes
=> Hotfix report performance

application/helpers/report_standard_params_occurrences.php, modules/cache_builder/config/cache_builder.php, modules/cache_builder/db/version_0_1_2/201512131953_occurrences_family_filter.sql
Makes family based (and all higher taxon based) filters much faster.
=> Family_taxa_taxon_list_id in cache_occurrences

application/config/version.php, modules/indicia_setup/db/version_0_9_1/201512211348_detail_groups.sql
Allows request join groups to have a public URL for requesting to join.
=> Groups view generates url_safe_titles for request groups

application/i18n/en_GB/general_errors.php, application/libraries/ReportEngine.php
Updates the report group by to included the sysfunc automatically added
attributes
=> Hotfix report errors

application/config/version.php, modules/summary_builder/config/summary_builder.php, modules/summary_builder/helpers/summary_builder.php, modules/summary_builder/views/summariser_definition/summariser_definition_edit.php
Changes to way estimates are created in the summary builder module, following discussion with UKBMS
=> Hotfix summary builder estimates

reports/reports_for_prebuilt_forms/pantheon/horus_indices_summary.xml, reports/reports_for_prebuilt_forms/pantheon/isis_summary.xml, reports/reports_for_prebuilt_forms/pantheon/osiris_summary.xml, reports/reports_for_prebuilt_forms/pantheon/results_overview_ecological_output.xml, reports/reports_for_prebuilt_forms/pantheon/results_overview_taxonomic_output.xml, reports/reports_for_prebuilt_forms/pantheon/sample_species.xml
=> Hotfix pantheon

reports/library/groups/groups_list.xml
* Does not show private groups in list available to join.
* Allows group_type_id parameter to be a comma separated list
=> Minor changes to groups list report

reports/library/groups/groups_list.xml
* Includes logo_path in fields.
=> Updated to match develop branch

application/libraries/ReportEngine.php, application/libraries/XMLReportReader.php
* Custom attributes for reports still respect the list of websites you
have permissions to when using sharing=me
* Code refactored and tidied
* Sharing mode=me respects website agreements rather than pulling in all
records.
=> Sharing mode=me tidy up

reports/reports_for_prebuilt_forms/Splash/get_my_squares_and_plots.xml, reports/reports_for_prebuilt_forms/Splash/get_my_squares_that_have_plots.xml, reports/reports_for_prebuilt_forms/Splash/get_plots_for_square_id.xml, reports/reports_for_prebuilt_forms/Splash/mean_cover_value_per_species_per_broad_habitat.xml, reports/reports_for_prebuilt_forms/Splash/mean_cover_value_per_species_per_fine_habitat.xml, reports/reports_for_prebuilt_forms/Splash/npms_sample_occurrence_samples.xml, reports/reports_for_prebuilt_forms/Splash/number_of_plots_per_species.xml, reports/reports_for_prebuilt_forms/Splash/occupied_squares_per_species.xml, reports/reports_for_prebuilt_forms/Splash/species_richness_per_broad_habitat.xml, reports/reports_for_prebuilt_forms/Splash/species_richness_per_fine_habitat.xml, reports/reports_for_prebuilt_forms/Splash/square_details_per_year.xml, reports/reports_for_prebuilt_forms/Splash/squares_per_habitat.xml
Some of the changes for NPMS 2016
=> Feature npms 2016

reports/library/groups/groups_list.xml, reports/library/locations/my_sites_lookup.xml
Report updates to support group hierarchies in locations lookup.
=> Hotfix group reports

application/libraries/DateParser.php
Mktime not reliable pre-1901 (depends on OS). So converted all date parsing code to use date class instead.
=> Fixes historic date parsing

reports/library/groups/groups_list.xml
Allows control over display of expired or upcoming groups.
=> Adds a parameter to groups list report for date filtering

reports/library/locations/my_sites.xml
idlist parameter expected by the My Sites page on iRecord.
Fixes querying polygons on the map so the grid filters.
=> Added idlist parameter to report

modules/occurrence_associations/reports/library/occurrence_associations/filterable_explore_list.xml, modules/occurrence_associations/reports/library/occurrence_associations/filterable_explore_list_mapping.xml, modules/occurrence_associations/reports/library/occurrence_associations/filterable_explore_list_mapping_lores.xml
Association and association details fields now concatenated into a
single field rather than outputting duplication occurrence rows if more
than 1 association.
=> Association fields now aggregated

modules/cache_builder/config/cache_builder.php
reporting cache tables were showing some reappearance of deleted
occurrences.
=> Prevent deleted occurrences reappearing

modules/summary_builder/config/summary_builder.php, modules/summary_builder/helpers/summary_builder.php
UKBMS Annual Summary summary_builder: ensure taxa with no data are removed from the summary (esp when processing deletes)
=> UKBMS Annual Summary summary_builder bugfix

application/libraries/XMLReportReader.php, reports/reports_for_prebuilt_forms/COCoast/occurrence_images/filterable_explore_list.xml, reports/reports_for_prebuilt_forms/COCoast/occurrences/filterable_explore_list.xml, reports/reports_for_prebuilt_forms/COCoast/occurrences/filterable_explore_list_mapping.xml, reports/reports_for_prebuilt_forms/COCoast/occurrences/filterable_explore_list_mapping_lores.xml, reports/reports_for_prebuilt_forms/COCoast/occurrences/filterable_occurrences_download_gis.xml, reports/reports_for_prebuilt_forms/COCoast/occurrences/filterable_occurrences_download_parent_samples.xml, reports/reports_for_prebuilt_forms/COCoast/taxa/filterable_explore_list.xml, reports/reports_for_prebuilt_forms/COCoast/taxa/filterable_explore_list_taxonomy_breakdown.xml, reports/reports_for_prebuilt_forms/COCoast/taxon_groups/filterable_explore_list.xml
Whole load of new Capturing our Coast reports
=> Hotfix co coast reports

reports/reports_for_prebuilt_forms/NHM/filterable_explore_list.xml, reports/reports_for_prebuilt_forms/NHM/filterable_explore_list_mapping.xml, reports/reports_for_prebuilt_forms/NHM/filterable_explore_list_mapping_lores.xml, reports/reports_for_prebuilt_forms/NHM/filterable_occurrences_download.xml, reports/reports_for_prebuilt_forms/NHM/filterable_samples_download.xml, reports/reports_for_prebuilt_forms/NHM/nhm_sample_location_names.xml
New reports for the NHM Big Seaweed Search project
=> Hotfix nhm reports

modules/audit/README.txt, modules/audit/controllers/logged_action.php, modules/audit/db/version_1_1_0/201508010900_schema.sql, modules/audit/db/version_1_1_0/201508010901_tables.sql, modules/audit/db/version_1_1_0/201508010902_functions.sql, modules/audit/db/version_1_1_0/201508010903_triggers.sql, modules/audit/db/version_1_1_0/201508010904_grid_view.sql, modules/audit/dbuninstall/remove_auditing.sql, modules/audit/models/gv_logged_action.php, modules/audit/models/logged_action.php, modules/audit/plugins/audit.php, modules/audit/views/logged_action/gridview.php, modules/audit/views/logged_action/index.php, modules/audit/views/logged_action/logged_action_read.php, modules/audit/views/logged_action/logged_action_readTL.php
=> Feature audit trail

application/helpers/report_standard_params_occurrences.php, application/models/group_page.php, application/models/groups_user.php, modules/indicia_setup/db/version_1_1_0/201605201414_group_page_access_levels.sql, modules/indicia_setup/db/version_1_1_0/201605201523_group_page_access_level_views.sql, modules/taxon_designations/plugins/taxon_designations.php, reports/library/groups/group_members.xml, reports/library/groups/groups_list.xml
=> Feature group pages access

modules/summary_builder/helpers/summary_builder.php
Summary builder module: reposition lastval initialisation and remove limit change for deleted locations. (1) is required so can process more than one survey each invocation of scheduled tasks: UKBMS now has 3 active.
=> Summary builder module: bugfix

reports/reports_for_prebuilt_forms/UKBMS/ukbms_section_plot.xml, reports/reports_for_prebuilt_forms/UKBMS/ukbms_year_plot_count.xml, reports/reports_for_prebuilt_forms/UKBMS/ukbms_year_plot_index.xml
New Reports for New UKBMS chart pages: section plot, year on year count/index plot
=> New Reports for new UKBMS chart pages

application/config/version.php, modules/data_cleaner/controllers/services/data_cleaner.php
Fixes errors in the Data Cleaner verify service picked up by unit testing.
=> Hotfix data cleaner verify

reports/reports_for_prebuilt_forms/UKBMS/ebms_country_locations.xml
New report to allow EBMS to find sites within countries.
=> UKBMS: new report to for EBMS

modules/indicia_svc_data/controllers/services/data.php
Brings location_attribute_values into line with equivalent sample,
occurrence and survey attributes
=> Allow location_attribute_values to be updated via the services

application/config/version.php, application/controllers/scheduled_tasks.php, modules/species_alerts/plugins/species_alerts.php
=> Hotfix occdelta crud

application/config/version.php, application/helpers/report_standard_params_occurrences.php, application/helpers/report_standard_params_samples.php, application/libraries/XMLReportReader.php
Fixes https://github.com/BiologicalRecordsCentre/iRecord/issues/117
=> Hotfix report params

modules/occurrence_associations/reports/library/occurrence_associations/filterable_explore_list.xml, modules/occurrence_associations/reports/library/occurrence_associations/filterable_explore_list_mapping.xml, modules/occurrence_associations/reports/library/occurrence_associations/filterable_explore_list_mapping_lores.xml, reports/library/occurrence_comments/filterable_explore_list.xml, reports/library/occurrence_images/filterable_explore_list.xml, reports/library/occurrences/explore_list.xml, reports/library/occurrences/explore_list_2.xml, reports/library/occurrences/explore_list_2_mapping.xml, reports/library/occurrences/explore_list_2_mapping_using_spatial_index_builder.xml, reports/library/occurrences/explore_list_2_using_spatial_index_builder.xml, reports/library/occurrences/explore_list_3_mapping_using_spatial_index_builder.xml, reports/library/occurrences/explore_list_3_using_spatial_index_builder.xml, reports/library/occurrences/explore_list_using_spatial_index_builder.xml, reports/library/occurrences/filterable_explore_list.xml, reports/library/occurrences/filterable_explore_list_blurred.xml, reports/library/occurrences/filterable_explore_list_mapping.xml, reports/library/occurrences/filterable_explore_list_mapping_blurred.xml, reports/library/occurrences/filterable_explore_list_mapping_lores.xml, reports/library/occurrences/filterable_visual_list.xml, reports/reports_for_prebuilt_forms/COCoast/occurrence_images/filterable_explore_list.xml, reports/reports_for_prebuilt_forms/COCoast/occurrences/filterable_explore_list.xml, reports/reports_for_prebuilt_forms/COCoast/occurrences/filterable_explore_list_mapping.xml, reports/reports_for_prebuilt_forms/COCoast/occurrences/filterable_explore_list_mapping_lores.xml, reports/reports_for_prebuilt_forms/NHM/filterable_explore_list.xml, reports/reports_for_prebuilt_forms/NHM/filterable_explore_list_mapping.xml, reports/reports_for_prebuilt_forms/NHM/filterable_explore_list_mapping_lores.xml, reports/reports_for_prebuilt_forms/Shorewatch/shorewatch_records.xml, reports/reports_for_prebuilt_forms/UKBMS/ukbms_filterable_explore_list.xml, reports/reports_for_prebuilt_forms/UKBMS/ukbms_filterable_explore_list_mapping.xml, reports/reports_for_prebuilt_forms/UKBMS/ukbms_filterable_explore_list_mapping_lores.xml
=> Hotfix report recorder field

xsd/report.xsd
Adds a xml schema for the report.xml files. #216
=> Add report.xsd

reports/library/occurrence_comments/filterable_explore_list.xml
=> Additions to library occurrence_comments report

modules/data_cleaner/db/version_1_55_0/20180105_detail_verification_rules.sql, modules/data_cleaner/plugins/data_cleaner.php
Expose the verification_rules and verification_rule_metadata tables on
the services, read only.
=> Data Cleaner updates

application/config/version.php, reports/reports_for_prebuilt_forms/UKBMS/ukbms_recorder_names.xml
Improves performance of recorder names lookup query considerably.
=> Hotfix recorder names lookup

modules/data_cleaner_period_within_year/plugins/data_cleaner_period_within_year.php, modules/notification_emails/plugins/notification_emails.php
Also changed message in email to refer to notifications.
=> Change to data cleaner phenology rule process

reports/reports_for_prebuilt_forms/UKBMS/ukbms_occurrence_download.xml, reports/reports_for_prebuilt_forms/UKBMS/ukbms_sample_download.xml, reports/reports_for_prebuilt_forms/UKBMS/ukbms_section_download.xml, reports/reports_for_prebuilt_forms/UKBMS/ukbms_summary_download.xml
Update to UKBMS Annual summary download reports reports on warehouse
(used by both ABLE/EBMS and UKBMS).
Reports were working OK when a location specified, but not when multiple
locations. Note that ABLE/EBMS has a separate occurrence download
report, in the brc-reports repository, which is OK.
=> ABLE Issue 156

application/config/version.php, application/controllers/scheduled_tasks.php
Fixes problem where species_alerts where not getting sent because the location_ids field wasn't being filled in quickly enough for occdelta.
=> Occdelta species alert fix

modules/summary_builder/helpers/task_summary_builder_location_delete.php, modules/summary_builder/helpers/task_summary_builder_sample.php
=> Boost batch sizes for location delete and sample jobs.

modules/rest_api/controllers/services/rest.php
This is just a draft pull request because I need to ensure that it merges okay with develop once https://github.com/Indicia-Team/warehouse/pull/355 is merged since both modify rest.php, but comments welcome now. These changes accept a value on the post data - `columnsSurveyId` - which is set to the ID of a survey for which custom survey & occurrence attributes are to be included in a download CSV and then ensure that the data is retrieved from the index and added to the downloaded data. Corresponding pull requests on media (https://github.com/Indicia-Team/media/pull/42) and client_helpers (https://github.com/Indicia-Team/client_helpers/pull/116).
=> Added handling for custom attributes for ES downloads

application/config/indicia_dist.php, modules/rest_api/controllers/services/rest.php
@johnvanbreda - this is a draft pull request at this stage. I am going to add some comments on reference problem that I can't solve.
=> Fixes to MapMate download format

modules/auto_verify/plugins/auto_verify.php
=> Auto-verify exception when no new records

application/config/version.php
Updates client_helpers from 6.2.0 to 6.2.3 and media from 6.2.0 to 6.2.1.
Fixes #392.
=> Update submodules to fix importer field matching

application/config/version.php, modules/cache_builder/db/version_6_2_9/202108271715_ix_cache_taxa_taxon_lists_preferred_taxon.sql, modules/data_cleaner_period_within_year/plugins/data_cleaner_period_within_year.php
=> Hotfix slow verification import

application/config/version.php, modules/data_cleaner/models/verification_rule.php
=> Hotfix verification cache

reports/reports_for_prebuilt_forms/species_details/occurrences_thumbnails_2.xml
Searches on external_key instead of taxon_meaning_id Only returns thumbnails associated with verified records Excludes those associated with confidential records
=> Added occurrences_thumbnails_2 report

reports/reports_for_prebuilt_forms/species_details/occurrences_thumbnails_2.xml
Adds new occurrence thumbs report. Filters on taxon external_key, excludes images assoicated with confidential records and includes only images associated with verified records.
=> Hotfeature occurrence thumbs 2

application/config/version.php, modules/indicia_setup/db/version_8_20_0/202306021401_recording_scheme_tables.sql
@johnvanbreda. Can you have a look at these table definitions? I'm unsure about a few things such as whether or not the fields are named as you would like, constraints etc.
=> Added tables linking RSS to taxa

application/config/version.php, modules/indicia_setup/db/version_9_1_11/202405090906_taxa_authority_length_increase.sql
To remove 100 character limit on taxa table's authority field.
=> Hotfix uksi taxon authority

application/config/version.php, modules/indicia_setup/db/version_9_1_11/202405090906_taxa_authority_length_increase.sql
Required for latest UKSI update
=> Update taxa.authority to remove 100 character restriction

application/models/sample.php, modules/cache_builder/config/cache_builder.php, modules/cache_builder/db/version_9_5_0/202410270900_cache_samples_import_guid.sql, modules/indicia_setup/db/version_9_5_0/202410270900_fields_for_import_reverser.sql, modules/indicia_setup/db/version_9_5_0/202410270900_fields_for_import_reverser.sql.sql, modules/indicia_svc_import/controllers/services/import_2.php, reports/library/imports/changed_occs_since_import.xml, reports/library/imports/changed_smps_since_import.xml, reports/library/imports/reversible_imports_list.xml
Importer reverser.
Also fixed a bug where the "updated" filed in the imports table was always 0.
Note this works with new code for client_helpers also.
=> Import reverse code.
