Indicia-Team/warehouse

reports/library/occurrences/filterable_nbn_exchange.xml

NBN Exchange format now includes the group that a record came from.
This can include the parent group (so a Consultancy/Project hierarchy
is exported).

Added group source column

---

modules/cache_builder/config/cache_builder.php

Records are considered answered now if ANY change is made after the
query comment. It used to be only if there was a further comment.

Change to when records are considered answered

---

application/libraries/ReportEngine.php
application/views/report/index.php
modules/indicia_svc_data/controllers/services/report.php

Requesting report metadata now possible via requestMetadata service.

Report services support for metadata

---

application/config/version.php
application/models/occurrence.php
application/models/sample.php

If a record was verified as V1 or V2, then edited on a single record
form that had a hidden input setting occurrence:record_status to 'C'
then this forcing of the record status prevented the code firing on
the occurrence (or sample) model to correctly clean out the prior
verification status. This could result in incorrect status + substatus
combinations.

Fix possible incorrect record substatuses

---

reports/library/occurrences/filterable_nbn_exchange.xml
reports/library/occurrences/filterable_occurrences_download.xml
reports/library/occurrences/filterable_occurrences_download_gis.xml
reports/library/occurrences/filterable_occurrences_download_parent_samples.xml
reports/library/occurrences/filterable_occurrences_download_sensitive.xml

Only outputs the VC if the record is fully contained within.
Therefore no need to aggregate if records overlap boundaries.

For #21, removes aggregation on VC column for performance

---

reports/library/occurrences/filterable_nbn_exchange.xml
reports/library/occurrences/filterable_occurrences_download.xml
reports/library/occurrences/filterable_occurrences_download_gis.xml
reports/library/occurrences/filterable_occurrences_download_parent_samples.xml
reports/library/occurrences/filterable_occurrences_download_sensitive.xml
reports/library/occurrences/nbn_exchange.xml
reports/library/occurrences/nbn_exchange_by_input_date.xml
reports/library/occurrences/nbn_exchange_by_input_date_using_spatial_index_builder.xml

* Faked “compound” VCs, used to allocate verifiers e.g. to Sussex or
Yorkshire, were causing duplication in download report outputs. Fixed.
* Correct latitude restrictions for NBN downloads

Hotfix nbn downloads

---

application/libraries/XMLReportReader.php
reports/library/occurrence_images/explore_list.xml
reports/library/occurrence_images/explore_list_2.xml
reports/library/occurrence_images/explore_list_using_spatial_index_builder.xml
reports/library/occurrences/cached_occurrence_list_for_location_boundary.xml
reports/library/occurrences/occurrences_list.xml
reports/library/occurrences/occurrences_list_for_cms_user.xml
reports/library/samples/filterable_explore_list.xml
reports/library/samples/filterable_explore_list_mapping.xml
reports/library/samples/filterable_samples_download_gis.xml
reports/library/taxa/explore_list.xml
reports/library/taxa/explore_list_2.xml
reports/library/taxa/explore_list_2_using_spatial_index_builder.xml
reports/library/taxa/explore_list_3_using_spatial_index_builder.xml
reports/library/taxa/explore_list_using_spatial_index_builder.xml

After recent performance revisions the o.sample_id field was being used
to join to get sample attributes which was not correct for pure sample
reports.

Ensured that all reports link smpattr parameters correctly

---

modules/occurrence_associations/models/occurrence_association.php

Resaving an association with known to_occurrence_id was not
working as the regex picked up standard integer foreign keys
and treated them as a pointer to a not-yet existing occurrence.

Corrected regular expression

---

reports/library/occurrences/nbn_exchange.xml
reports/library/occurrences/nbn_exchange_by_input_date.xml
reports/library/occurrences/nbn_exchange_by_input_date_using_spatial_index_builder.xml

Older versions of NBN download reports tidied to remove unnecessary join
to occurrences table, plus filters use the cache_occurrences table where
possible.

Report performance

---

reports/library/occurrences/filterable_nbn_exchange.xml
reports/library/occurrences/filterable_occurrences_download.xml
reports/library/occurrences/filterable_occurrences_download_gis.xml
reports/library/occurrences/filterable_occurrences_download_parent_samples.xml
reports/library/occurrences/filterable_occurrences_download_sensitive.xml
reports/library/occurrences/nbn_exchange.xml
reports/library/occurrences/nbn_exchange_by_input_date.xml
reports/library/occurrences/nbn_exchange_by_input_date_using_spatial_index_builder.xml

Fixes a problem where a record which overlaps with a genuine vice county as well as a "fake supercounty" like Yorkshire or Sussex would get
included twice in download reports.

Report download duplicate fixes

---

modules/indicia_setup/db/version_0_9_1/201602041346_comment_external_keys.sql

Allows tracking of comments which were synced from other systems, e.g.
verification decisions.

External key columns for comments tables

---

modules/occurrence_associations/reports/library/occurrence_associations/filterable_explore_list.xml

This tags records on the "left" side of associations as editable, as
those on the "right" side are entered into the same form so shouldn't be
accessed directly on the edit page. Therefore you can use the output of
this field to control the visibililty of edit actions in report grids.

Added a can_edit column to occurrences associations list report

---

modules/indicia_setup/db/version_0_9_1/201603132027_sref_system_to_srid.sql
modules/sref_mtb/plugins/sref_mtb.php

Should be 4314, not 4745 which only covers part of east Germany.

Corrected SRID for German MTB reference system

---

modules/indicia_setup/db/version_0_9_1/201603301140_detail_samples_vague_dates.sql

This allows correct reloading of samples with vague dates rather than just using the start date.

Detail_samples.display_date column

---

modules/indicia_setup/db/version_0_9_1/201603311022_detail_samples_vague_dates.sql

For standard dates (not vague), display date returned in ISO format and this allows the client to reformat to localised settings.

detail_samples.display_date output

---

application/models/location.php
application/models/occurrence.php
application/models/sample.php
application/views/report/params.php
modules/indicia_svc_import/controllers/services/import.php

Change to allow fetching of sample_method or location_type specific attributes when using upload into warehouse.
Also fixes an issue when using an sref or location_typ/sample_method with a comma or colon in it: these special characters are used by explode elsewhere in the code.
Must be accompanied by the equivalent pull into master for the client_helpers submodule, and that included in the deployment.

Uploads: fetching of sample_method or location_type specific attributes as field options

---

modules/indicia_setup/db/version_0_9_1/201604040855_locations_views.sql

Allows locations that were previously linked to a website to become public by mark deletion of locations_websites records rather than physical deletion.

Locations views check delete flag on locations_websites

---

reports/library/occurrences/filterable_explore_list_mapping.xml

Allows exclusion of large grid squares (e.g. 100km) from zoomed in maps.

Adds max_sq_size parameter to full res filterable map report

---

reports/library/groups/groups_list.xml

Allows looking up the group hierarchy, e.g. for Breadcrumb population.

Adds a to_group_id parameter to the groups_list report

---

reports/library/taxa/filterable_explore_list_multi_checklist.xml

Maps the taxa reported back to a single master checklist which means
species names are not duplicated if there are variations between several
checklists in how they write the names.

New filterable taxon report

---

application/libraries/MY_ORM.php
application/models/occurrence.php
application/models/sample.php
application/views/importer.php
modules/indicia_svc_import/controllers/services/import.php

supermodels (e.g. occurrences has samples). Fix exception when FK lookup
by ID fails. Add sample_method to occurrence fixed_value_form along with
FK filters for location location_type and parent sample sample_method.
Add fk parent sample and location lookups by external key for sample CSV
upload, and in fixed_value_form add FK filter for parent sample
sample_method.

Fix handling of FK and parents in CSV uploads where model has

---

application/libraries/ReportEngine.php

When outputing multi-value attributes, do not include deleted attribute
values in the array.

ReportEngine: Deleted multi-value attributes

---

modules/cache_builder/config/cache_builder.php
modules/cache_builder/db/version_1_6_1/201609081300_subsample_input_form.sql

Use the value held in the parent sample, for both subsamples and
occurrences.

Cache_builder: populate the input_form field in subsample situations

---

reports/reports_for_prebuilt_forms/UKBMS/ukbms_species_and_occurrence_counts_with_code.xml

Without a WHERE clause in the report the filters become part of the
JOINs, not the main query. When the JOINs include an (optional) LEFT
JOIN attribute, this means the filter is not applied to the main query.

UKBMS Species/Occurrence Report: fix filtering.

---

reports/library/groups/groups_list.xml

The Groups_list library report has been extended to allow the handling
of a CMS based permission for adminstrators, to allow such
administrators to edit groups even if they are not members of the group.
iRecord Issue 52.

Groups_list report takes CMS administrator Premission

---

reports/reports_for_prebuilt_forms/UKBMS/ukbms_branch_walks_list.xml
reports/reports_for_prebuilt_forms/UKBMS/ukbms_my_walks_list.xml

Main change is removal of location_type_id param from branch report, see
UKBMS Issue 42: the selection of walks is driven by the survey_id, not
the location type. Also removes smpattrs from my walks as not used.

Make My Walks and Branch Walks reports consistent.

---

application/config/version.php
application/controllers/trigger.php

Addresses https://github.com/Indicia-Team/warehouse/issues/304
Uses the ReportEngine->reportList function to obtain a list of all available reports including those provided by custom modules.
Extracts trigger templates from this list and builds a files array compatible with the one previously returned by the function.
Improves on the previous version by presenting the report title rather than the file name to the user.

Enable selection of trigger_templates from warehouse modules

---

application/controllers/forgotten_password.php
application/controllers/scheduled_tasks.php
modules/indicia_auth/libraries/Auth.php
modules/notification_emails/plugins/notification_emails.php

Addresses Warehouse issue https://github.com/Indicia-Team/warehouse/issues/323.
Updated a number of Warehouse classes so that they do not attempt to send emails if a do_not_send config variable is set to true  in the application/config/email.php file. The code will work as at present if that variable is not set in the config file or if it is set to false. But if it is set to true, emails are not sent.
If email is not configured properly, code breaks at the point where it connects to the email service: `email::connect()`. I found that pattern in six PHPfiles and I updated four of them to check for the config setting and return silently (although logging an info message) if it is set without actually sending email. I have only actually tested on my localhost for situations were Indicia user …

Don't send emails if do_not_send email config set

---

application/helpers/vague_date.php
application/tests/helpers/vague_dateTest.php

Updated string_to_vague_date function so that it returns vague_date via call to a function called validate which returns false if invalid and returns the vague_date if okay. Currently function only checks to ensure that end date is after start date.
This validate function actually already existed in the code but did nothing (empty body). However it was called from the vague_date_to_string function. I commented this call out. It seems that function relies on format-specific functions it calls to validate stuff.
Added a couple of tests to the units tests to test for end date before start date.

Fix for system allowing vague dates were start after end date

---

modules/summary_builder/config/summary_builder.php
modules/summary_builder/helpers/task_summary_builder_sample.php

The logic prevent the extra calculations is too restrictive, and seems
to cause issues when processing several samples on the same location at
the same time.
This extra check has been removed: it may mean that in a few cases the
summary calculations will be repeated, but from a performance viewpoint
there should also be a speedup as the queries are simplified for every
sample and occurrence.

UKBMS Issue 119

---

application/config/version.php
application/controllers/survey.php
application/models/survey.php
application/views/survey/survey_edit.php
modules/auto_verify/db/version_2_36_0/201910071330_new_survey_fields.sql

@johnvanbreda - this is not for merging. It's just so you can review the code and I can ask you a question about it.
This includes everything necessary to be able to specify taxa against surveys that will be used as filters for auto-verification. I haven't touched the auto-verification yet.
It all works and looks like the image below. But I think that there might be a better way to populate `$otherData['taxon_restrictions']` from the DB - I'll add a comment/question on the relevant code below.

Added Warehouse features for Survey auto-verify filtering

---

modules/auto_verify/plugins/auto_verify.php

Addition to the auto-verify SQL to further restrict qualifying occurrences to those for taxa in, or descended from taxa in, a list stored against a survey. Addresses issue: https://github.com/BiologicalRecordsCentre/iRecord/issues/486
See also: https://github.com/Indicia-Team/warehouse/pull/335

Update auto_verify to take account of taxon restrictions

---

application/controllers/survey.php
application/views/survey/survey_edit.php

Fixes a non-critical bug in previous implementation of the taxon checklist control on in survey_edit that causes fields for occurrence attributes to be displayed.

Corrects a bug in survey_edit.php

---

application/models/location.php
application/models/occurrence.php
application/models/sample.php
modules/indicia_svc_import/controllers/services/import.php

Following changes to import:
Samples: Don't force entry of an sref if a location id provided
Samples: Allow the location to be referenced by its Indicia ID
Locations: Allow the parent location to be referenced by its Indicia ID
Occurrences: Don't force entry of an taxon name when specifying the taxon by its Indicia TTLID,
See https://github.com/BiologicalRecordsCentre/UKBMS-online/issues/125

Feature : Import changes for UKBMS

---

modules/rest_api/controllers/services/rest.php

@johnvanbreda this is to include the new ES fields (input_sref and input_sref_system) in the easy-download compatible format.

Update to include new ES fields in easy-download format

---

modules/rest_api/controllers/services/rest.php

@johnvanbreda - the title of the branchis a bit of a misnomer - this now is dealing with MapMate and changes to the Backward-compatibility formatting.
I've handled the MapMate special fields, and those needed for Backward compatibility a bit differently. In general, I've used separate special fields for MapMate but for the Backward compatibility, I've dealt with them altogether in a single '#backward:<field># field handler. If you've a strong preference about using one or the other way and want me to modify, let me know.
I've also run into a problem which I've spent several hours investigating but not resolved yet - you may be able to save me some time. If I download a large 'backward-compatible' file over 5000 records, the first 5000 records in the correct format, but the rest in the …

Iss 886 mapmate and backward compat download format handling

---

application/config/version.php
modules/data_cleaner/helpers/data_cleaner.php
modules/data_cleaner/tests/helpers/data_cleanerTest.php
modules/data_cleaner/tests/rule_files/ancillary_species.txt
modules/data_cleaner/tests/rule_files/id_difficulty.txt
modules/data_cleaner/tests/rule_files/period.txt
modules/data_cleaner/tests/rule_files/period_within_year.txt
modules/data_cleaner/tests/rule_files/period_within_year_with_stage.txt
modules/data_cleaner/tests/rule_files/without_polygon.txt
modules/data_cleaner_without_polygon/plugins/data_cleaner_without_polygon.php

Fixes #390 - AncillarySpecies verification rules not being applied.
Fixes #395 - Script aborted importing verification rules.

Hotfix verification rules

---

application/config/version.php
modules/data_cleaner/controllers/verification_rule.php
modules/data_cleaner/models/verification_rule.php

Fixes #397 - cache_verification tables not being updated
There are two paths to modifying verification rules, one directly via the website UI, the other by importing from files.
The updating of caches is moved to a function and called from both paths.

cache_verification tables not being updated

---

modules/rest_api/controllers/services/rest.php
modules/rest_api/entities/location.json
modules/rest_api/tests/Rest_ControllerTest.php

Fixes #407 
- Adds a missing method for /locations end point, limiting the list to locations for the user and website.
- Adds a filter to the /locations/id endpoint so that locations are restricted by the website for the user. Also allows public locations to be returned.
- Fixes an error in processing the allowed scopes supplied in the JWT payload.

Fix for REST API locations end point

---

reports/library/taxa/taxon_names_2.xml

Hotfix to taxon-names-2 report to retrieve taxon name without italicisation and addition of authority.

Add retrieval of unaltered taxon name to report

---

reports/library/taxa/taxon_names_2.xml

Retrieve taxon name without addition of italics and authority.

Hotfix taxon names 2 report

---

modules/uksi_operations/controllers/uksi_operation.php

Did update to uksi_operations module to directly populate ttl.common_taxon_id from current taxon for these two operations: processAddSynonym and processRenameTaxon. A third operation where ORM taxa_taxon_list model is called is processNewTaxon but since it doesn't reference any existing taxa, I did not update it.

Populate ttl.common_taxon_id from current taxon

---

reports/reports_for_prebuilt_forms/sample_details/sample_data.xml

This still has problems relating to the use of the Allow Unreleased checkbox due to difficulties with reports_for_prebuilt_forms/samples_details/occurrences_list (see email I sent 27/5/2025 15:45), but things are better than before.
Requesting review because it involves confidentiality, and I wanted to make sure you are ok with what have done.
Improved behaviour
1.
Old behaviour
Incorrectly - Doesn't show Sample Details page when no occurrences are present unless both the Allow Confidential and Allow Unreleased checkboxes are on.
New behaviour
Correctly - shows Sample Details page when no occurrences are present regardless of checkbox settings
2.
Old behaviour
If only some records are confidential and the Allow Confidential box is off, then the Sample Details page is shown with …

Sample details - Now allows viewing when no occs

---

reports/reports_for_prebuilt_forms/sample_details/extra_geoms_for_child_parent_sample_details.xml
reports/reports_for_prebuilt_forms/sample_details/extra_geoms_for_parent_child_sample_details.xml
reports/reports_for_prebuilt_forms/sample_details/sample_data.xml

Hi,
Quite a lot of changes to the logic on the sample details form.
1. Fixes problem where if an unreleased occurrence is sensitive, no blurring would occur on the map (commit 1883b8c).
2. When there are sensitive occurrences, make sure no location geometries are shown on the map at all (commit 79ac99b)
3. Make sure unreleased occurrence points do not appear on map. 
This is most obviously noticeable if there is a parent sample loaded onto Sample Details, and that sample has child samples, and one of the subsamples has all of its occurrences unreleased (commit d4d7431)
(also includes a minor fix to the "type" column which I forgot to mention in the git commit message)
4. Similar, but instead of unreleased, it is sensitive occurrence points we want to avoid showing (Commit 086645e).
5. …

Sample Details map logic changes
